apiVersion: v1
kind: Service
metadata:
  namespace: staging
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -o k8s/base/
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cast-service
  name: cast-service
spec:
  ports:
  - name: "8002"
    port: 8002
    targetPort: 8000
  selector:
    io.kompose.service: cast-service
status:
  loadBalancer: {}
